version: "3"

name: smarthomeserver

# a couple of services for your smarthome, remember to set up your .env file first
services:
  grafana:
    image: "grafana/grafana:latest"
    restart: unless-stopped
    user: "$PUID:$PGID"
    depends_on:
      influxdb:
        condition: service_healthy
    volumes:
      - "${DATADIR}/grafana/data:/var/lib/grafana"
      - "./configs/grafana.ini:/etc/grafana/grafana.ini"
    ports:
      - 3000:3000
    # uncomment this if you wanta to allow anonymus acces to Grafana for embedding (e.g. in Home Assistant dashboards)
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_SECURITY_ALLOW_EMBEDDING=false
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"

  influxdb:
    image: "influxdb:latest"
    restart: unless-stopped
    volumes:
      - ${DATADIR}/influxdb/data:/var/lib/influxdb2:rw
    healthcheck:
      test: [ "CMD", "curl", "-sI", "http://localhost:8086/ping" ]
      interval: 30s
      timeout: 1s
      retries: 24
    ports:
      - 8086:8086
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "http://loki:3100/loki/api/v1/push"

  telegraf:
    image: telegraf_fronius
    user: root
    build:
      context: ./telegraf-exec-fronius
      dockerfile: Dockerfile
    restart: always
    volumes:
      - "${DATADIR}/telegraf.conf:/etc/telegraf/telegraf.conf:ro"
      - "/mnt:/mnt:ro"
      # - /:/hostfs:ro
    devices:
      - /dev/sdb2:/dev/sdb2
      #   - /dev/sda:/dev/sda
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '8125:8125'
    environment:
      - OPENWEATHERMAP_API_KEY=$OPENWEATHERMAP_API_KEY
      - INFLUXDB_TOKEN=$INFLUXDB_TOKEN
      - MQTT_USER=$MQTT_USER
      - MQTT_PASSWORD=$MQTT_PASSWORD
      # - HOST_ETC=/hostfs/etc
      # - HOST_PROC=/hostfs/proc
      # - HOST_SYS=/hostfs/sys
      # - HOST_MOUNT_PREFIX=/hostfs
      # logging:
      #   driver: loki
      #   options:
      #     loki-url: "http://loki:3100/loki/api/v1/push"

  mosquitto:
    image: "eclipse-mosquitto:latest"
    restart: unless-stopped
    volumes:
      - "${DATADIR}/mosquitto/config:/mosquitto/config"
      - "${DATADIR}/mosquitto/data:/mosquitto/data"
      - "${DATADIR}/mosquitto/log:/mosquitto/log"
    ports:
      - 1883:1883
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "http://loki:3100/loki/api/v1/push"

  homeassistant:
    container_name: homeassistant
    restart: unless-stopped
    image: "ghcr.io/home-assistant/home-assistant:stable"
    #devices:
    #  - /dev/ttyUSB0:/dev/ttyUSB0
    #  - /dev/ttyUSB1:/dev/ttyUSB1
    #  - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - ${DATADIR}/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /dev/serial/by-id/:/dev/serial/by-id/
    # alternative needed for auto discovery, bluetooth,...
    #network_mode: host
    #privileged: true
    depends_on:
      influxdb:
        condition: service_healthy
      mosquitto:
        condition: service_started
    ports:
      - 8123:8123
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      # don't automatically update this container as it might break your setup
      - "com.centurylinklabs.watchtower.enable=false"
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "http://loki:3100/loki/api/v1/push"

  homebridge:
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - "${DATADIR}/homebridge:/homebridge"
    # ports:
    #   - 8581:8581
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "http://loki:3100/loki/api/v1/push"

  loki:
    container_name: loki
    image: grafana/loki:2.8.0
    restart: unless-stopped
    ports:
      - 3100:3100
    volumes:
      - ${DATADIR}/loki-config.yaml:/etc/loki/loki-config.yaml
      # - ${DATADIR}/loki/data:/data/loki
      # - ${DATADIR}/loki/wal:/wal
    command: -config.file=/etc/loki/loki-config.yaml
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "http://loki:3100/loki/api/v1/push"
    #     max-size: "200m"
    # ingest:
    #   wal:
    #     dir: "/tmp/wal"

  promtail:
    container_name: promtail
    image: grafana/promtail:2.8.0
    restart: unless-stopped
    volumes:
      - /var/snap/docker/common/var-lib-docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - ${DATADIR}/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      # to read container labels and logs
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail-config.yaml

  heimdall:
    image: linuxserver/heimdall:2.5.7
    container_name: heimdall
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DATADIR}/heimdall:/config
    ports:
      - 9080:80
      - 9443:443
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "http://loki:3100/loki/api/v1/push"

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=true # deleting old unused images automatically
      # optional for notifications
      #- WATCHTOWER_NOTIFICATIONS=email
      #- WATCHTOWER_NOTIFICATION_EMAIL_FROM=${EMAIL_FROM}
      #- WATCHTOWER_NOTIFICATION_EMAIL_TO=${WATCHTOWER_EMAIL_TO}
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${SMTP_SERVER}
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${SMTP_PORT}
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${SMTP_USER}
      #- WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${SMTP_PASSWORD}
      # alternative for notification via pushover
      #- WATCHTOWER_NOTIFICATIONS=shoutrrr
      #- WATCHTOWER_NOTIFICATION_URL=pushover://shoutrrr:${PO_TOKEN}@${PO_USERKEY}
      # logging:
      #   driver: loki
      #   options:
      #     loki-url: "http://loki:3100/loki/api/v1/push"
      # loki:
      #   container_name: loki
      #   image: grafana/loki:latest
      #   restart: unless-stopped
      #   ports:
      #     - "127.0.0.1:3100:3100"
      #   volumes:
      #     - ${DATADIR}/loki-config.yaml:/etc/loki/loki-config.yaml
      #     - ${DATADIR}/loki/data:/data/loki
      #   command: -config.file=/etc/loki/loki-config.yaml
      #   # logging:
      #   #   driver: loki
      #   #   options:
      #   #     loki-url: "http://localhost:3100/loki/api/v1/push"

      # can be used as an alternative to the Loki log driver
      # promtail:
      #   container_name: promtail
      #   image: grafana/promtail:2.3.0
      #   restart: unless-stopped
      #   volumes:
      #     - /var/lib/docker/containers:/var/lib/docker/containers:ro
      #     - ${DATADIR}/promtail/config/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      #   command: -config.file=/etc/promtail/promtail-config.yaml

  duplicati:
    image: lscr.io/linuxserver/duplicati:2.0.6
    container_name: duplicati
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      #- CLI_ARGS= #optional
    volumes:
      - ${DATADIR}/backups:/backups
      - ${DATADIR}/duplicati/config:/config
      - ${DATADIR}:/source
    ports:
      - 8200:8200
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "http://loki:3100/loki/api/v1/push"

  node-red:
    image: nodered/node-red:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    volumes:
      - ${DATADIR}/nodered:/data
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: "http://loki:3100/loki/api/v1/push"

    # pihole:
    #   image: pihole/pihole:latest
    #   restart: unless-stopped
    #   volumes:
    #     - "${DATADIR}/pihole/etc-pihole/:/etc/pihole/"
    #     - "${DATADIR}/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/"
    #   environment:
    #     - TZ=Australia/Adelaide
    #     - WEBPASSWORD=${PI_HOLE_ADMIN_PWD}
    #   ports:
    #     - 53:53/tcp
    #     - 53:53/udp
    #     - 67:67/udp
    #     - 80:80/tcp
    #     - 443:443/tcp
    #   cap_add:
    #     - NET_ADMIN
    #   # Note on ubuntu you need to
    #   # sudo sed -r -i.orig 's/#?DNSStubListener=yes/DNSStubListener=no/g' /etc/systemd/resolved.conf
    #   # sudo sh -c 'rm /etc/resolv.conf && ln -s /run/systemd/resolve/resolv.conf /etc/resolv.conf'
    #   # sudo systemctl restart systemd-resolved
  plex:
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    volumes:
      - "${DATADIR}/plex/config:/config"
      - "/mnt/external_hdd/TV:/data/tvshows"
      - "/mnt/external_hdd/Movies:/data/movies"
    environment:
      - PLEX_CLAIM="claim-LKcqnPkpUfSRPzYsmsVi"
      - ADVERTISE_IP="http://<hostIPAddress>:32400/"
    network_mode: host
    # ports:
    # - 32400:32400/tcp
    # - 3005:3005/tcp
    # - 8324:8324/tcp
    # - 32469:32469/tcp
    # - 1900:1900/udp
    # - 32410:32410/udp
    # - 32412:32412/udp
    # - 32413:32413/udp
    # - 32414:32414/udp
  webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop #optional
    volumes:
      - ${DATADIR}/webtop/config:/config
      - /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped

  timemachine:
    image: mbentley/timemachine
    restart: unless-stopped
    volumes:
      - /mnt/external_hdd/timemachine:/opt/${TM_USERNAME}
    ports:
      - "548:548"
      - "636:636"
    environment:
      - AFP_LOGIN=${AFP_LOGIN}
      - AFP_PASSWORD=${AFP_PASSWORD}
      - AFP_NAME=${AFP_NAME}
      - AFP_SIZE_LIMIT=${AFP_SIZE_LIMIT}
      - SMB_NAME=${SMB_NAME}
      - SMB_LOGIN=${SMB_LOGIN}
      - SMB_PASSWORD=${SMB_PASSWORD}
      - TM_USERNAME=${TM_USERNAME}
      - PASSWORD=${TM_PASSWORD}
    network_mode: host

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.0
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${DATADIR}/qbittorrent/config:/config
      - /mnt/external_hdd/Downloading:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
