services:
  traefik:
    image: traefik:v2
    restart: unless-stopped
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.network=homelab"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./configs/traefik:/etc/traefik/dynamic:ro"
    networks:
      - homelab
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9444:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - homelab
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.lab`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9443"
      - "traefik.http.services.portainer.loadbalancer.server.scheme=https"
      - "traefik.http.services.portainer.loadbalancer.serverstransport=skipverify@file"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  samba:
    image: mbentley/timemachine:smb
    restart: unless-stopped
    stop_grace_period: 15s
    network_mode: host
    environment:
      - CUSTOM_SMB_CONF=true
      - TM_USERNAME=${TM_USERNAME}
      - PASSWORD=${TM_PASSWORD}
      - TZ=${TZ}
    volumes:
      - /mnt/external_hdd/timemachine:/opt/timemachine
      - /mnt/external_hdd:/media
      - ./configs/smb.conf:/etc/samba/smb.conf
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  dnsmasq:
    image: andyshinn/dnsmasq:latest
    container_name: dnsmasq
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    command: --no-daemon --address=/.lab/${TAILSCALE_IP} --server=1.1.1.1 --server=1.0.0.1
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      - homelab
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  data:

networks:
  homelab:
    external: true
