http:
  serversTransports:
    skipverify:
      insecureSkipVerify: true

  middlewares:
    authelia:
      forwardAuth:
        address: "http://authelia:9091/api/verify?rd=https://auth.svc.lab/"
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email

  routers:
    plex:
      rule: "Host(`plex.lab`)"
      entryPoints:
        - websecure
      service: plex
      tls: {}

    homebridge:
      rule: "Host(`homebridge.lab`)"
      entryPoints:
        - websecure
      service: homebridge
      tls: {}

  services:
    plex:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:32400"

    homebridge:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:8581"

tls:
  certificates:
    - certFile: /etc/traefik/dynamic/certs/lab.crt
      keyFile: /etc/traefik/dynamic/certs/lab.key
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/dynamic/certs/lab.crt
        keyFile: /etc/traefik/dynamic/certs/lab.key
